#!/usr/bin/env python3

'''Async compresion module
'''
import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_generator() -> List[float]:
    '''Returns list generated by astnc_generator
    '''
    return [i async for  i in async_generator()]
